# Generated by Django 6.0.5 on 2026-05-10 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Coach', 'Coach'), ('Scout', 'Scout'), ('Medical', 'Medical'), ('Marketing', 'Marketing')], max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('cost', models.PositiveIntegerField(default=10000)),
                ('bonus', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(default=20)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('Allrounder', 'Allrounder'), ('Wicketkeeper', 'Wicketkeeper')], max_length=20)),
                ('bowling_type', models.CharField(choices=[('Fast', 'Fast'), ('Spin', 'Spin'), ('Medium', 'Medium'), ('None', 'None')], default='None', max_length=10)),
                ('batting', models.PositiveIntegerField(default=50)),
                ('bowling', models.PositiveIntegerField(default=50)),
                ('stamina', models.PositiveIntegerField(default=50)),
                ('fielding', models.PositiveIntegerField(default=50)),
                ('value', models.PositiveIntegerField(default=10000)),
                ('is_for_auction', models.BooleanField(default=False)),
                ('contract_expiry', models.PositiveIntegerField(default=30)),
                ('career_stats', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='StadiumConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.PositiveIntegerField(default=50)),
                ('pitch_type', models.CharField(default='Flat', max_length=50)),
                ('soil_type', models.CharField(choices=[('Red', 'Red'), ('Black', 'Black')], default='Red', max_length=10)),
                ('merchandise_revenue', models.PositiveIntegerField(default=1000)),
                ('capacity', models.PositiveIntegerField(default=8000)),
                ('seats_level', models.PositiveIntegerField(default=1)),
                ('food_level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.PositiveIntegerField(default=0)),
                ('end_time', models.DateTimeField()),
                ('starting_bid', models.PositiveIntegerField(default=0)),
                ('high_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='manager.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=10)),
                ('logo_url', models.URLField(blank=True)),
                ('jersey_color', models.CharField(blank=True, max_length=20)),
                ('currency_unit', models.CharField(choices=[('$', '$'), ('£', '£'), ('€', '€'), ('¥', '¥'), ('₹', '₹')], default='$', max_length=3)),
                ('fame', models.IntegerField(default=0)),
                ('currency', models.IntegerField(default=100000)),
                ('training_camp_level', models.PositiveIntegerField(default=1)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_teams', to='manager.personnel')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_teams', to='manager.personnel')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_teams', to='manager.personnel')),
                ('stadium', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.stadiumconfig')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='manager.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('score', models.JSONField(default=dict)),
                ('pitch_type', models.CharField(default='Flat', max_length=50)),
                ('soil_type', models.CharField(choices=[('Red', 'Red'), ('Black', 'Black')], default='Red', max_length=10)),
                ('scheduled_time', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='manager.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='manager.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.URLField(blank=True)),
                ('manager_level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
